name: 🐞 Report a Bug
description: Report a bug found in the application
type: "Bug"
body:
  - type: textarea
    id: description
    attributes:
      label: "Description:"
      value: |
        Describe the situation ...

        ### Current Behaviour:
        ...

        ### Expected Behaviour:
        ...
    validations:
      required: true
  - type: dropdown
    id: environments
    attributes:
      label: Which environments are affected?
      multiple: true
      options:
        - Prod
        - Dev
        - Local
