name: Report a Bug
description: Report a bug found in the application
title: "🐞 "
type: "Bug"
body: |
  ## Description:
  Describe the situation ...

  ### Current Behaviour:
  ...

  ### Expected Behaviour:
  ...