name: Bug Report
description: Report a bug in the project
title: "[Bug]: "
labels: ["bug"]
body: |
  ### Description
  _A clear and concise description of the bug._

  ---

  ### Steps to Reproduce
  1. Step one
  2. Step two
  3. Step three

  ---
  
  ### Expected Behavior
  _What you expected to happen._

  ---

  ### Screenshots
  _If applicable, add screenshots to help explain the problem._

  ---