name: New Feature
description: Request a new feature for the application
title: "New Feature"
type: "Feature"
body: |
  **As a** ...,
  **I need to** ...
  **so that** ...
  
  **Description:**
  Describe the new feature ...
  
  **CoA:**
  - [ ] ...
  - [ ] ...
