name: ✨ New Feature
description: Request a new feature for the application
type: "Feature"
body:
  - type: textarea
    id: description
    attributes:
      label: "Description:"
      value: |
        **As a** ...,
        **I need to** ...
        **so that** ...
        
        Describe the new feature ...
        
        **CoA:**
        - [ ] ...
        - [ ] ...
    validations:
      required: true