name: Technical Debt issue
description: Create a Technical debt issue.
title: "🛠️ "
type: "Feature"
labels: ["technical-debt"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      value: |
        ## Description:
        ...
    validations:
      required: true
