name: 🛠️ Technical Debt issue
description: Create a Technical debt issue.
type: "Task"
labels: ["technical-debt"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description:"
      value: |
        ...
    validations:
      required: true
